// Define furniture items
export const furnitureItems = [
  { id: 'sofa-2p', name: '2 Person Sofa', points: 10 },
  { id: 'sofa-3p', name: '3 Person Sofa', points: 12 },
  { id: 'armchair', name: 'Armchair', points: 5 },
  { id: 'chair', name: 'Chair', points: 3 },
  { id: 'coffee-table', name: 'Coffee Table', points: 6 },
  { id: 'desk', name: 'Desk', points: 8 },
  { id: 'dressoir', name: 'Dressoir', points: 7 },
  { id: 'paintings', name: 'Paintings', points: 2 },
  { id: 'secretaire', name: 'Secretaire', points: 9 },
  { id: 'small-furniture', name: 'Small Furniture', points: 4 },
  { id: 'boxes', name: 'Boxes', points: 1 },
  { id: 'carpet', name: 'Carpet', points: 3 },
  { id: 'closet', name: 'Closet', points: 10 },
  { id: 'cupboard', name: 'Cupboard', points: 8 },
  { id: 'dining-table', name: 'Dining Table', points: 12 },
  { id: 'large-chair', name: 'Large Chair', points: 5 },
  { id: 'plants', name: 'Plants', points: 3 },
  { id: 'side-table', name: 'Side Table', points: 4 },
  { id: 'tv', name: 'TV', points: 3 },
  { id: 'fridge', name: 'Fridge', points: 8 },
  { id: 'bed', name: 'Bed', points: 10 },
  { id: 'table', name: 'Table', points: 6 },
];

// City Day Data
export const cityDayData: { [key: string]: string[] } = {
Amsterdam: ["Monday", "Wednesday", "Friday"],
Rotterdam: ["Tuesday", "Thursday"],
TheHague: ["Saturday", "Sunday"],
Utrecht: ["Monday"],
Almere: ["Tuesday"],
Haarlem: ["Wednesday"],
Zaanstad: ["Thursday"],
Amersfoort: ["Friday"],
"s-Hertogenbosch": ["Saturday"],
Hoofddorp: ["Sunday"],
Breda: ["Monday", "Wednesday"],
Leiden: ["Tuesday", "Thursday"],
Dordrecht: ["Friday", "Sunday"],
Zoetermeer: ["Saturday"],
Delft: ["Monday", "Wednesday"],
Eindhoven: ["Tuesday", "Thursday"],
Maastricht: ["Friday", "Sunday"],
Tilburg: ["Saturday"],
Groningen: ["Monday", "Wednesday"],
Nijmegen: ["Tuesday", "Thursday"],
Enschede: ["Friday", "Sunday"],
Arnhem: ["Saturday"],
Apeldoorn: ["Monday", "Wednesday"],
Deventer: ["Tuesday", "Thursday"],
Zwolle: ["Friday", "Sunday"],
};
